package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;


public class Menu_Form extends javax.swing.JFrame {

    
    public Menu_Form() {
        initComponents();
        
        this.setLocationRelativeTo(this);
        this.jButton_Home.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton_Menu = new javax.swing.JButton();
        jLabel_close = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        pnmenu = new javax.swing.JPanel();
        jButton_Home = new javax.swing.JButton();
        jButton_ventas = new javax.swing.JButton();
        jButton_Productos = new javax.swing.JButton();
        jButton_Canchas = new javax.swing.JButton();
        jButton_Partidas = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        BN = new javax.swing.JPanel();
        jLabel_Fondo = new javax.swing.JLabel();

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/multimedia.png"))); // NOI18N
        jButton_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_MenuMouseClicked(evt);
            }
        });
        jButton_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MenuActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel_close.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
        });
        jPanel3.add(jLabel_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        jLabel_minimize.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel_minimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minimize.setText("-");
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
        });
        jPanel3.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        pnmenu.setBackground(new java.awt.Color(51, 51, 51));

        jButton_Home.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa.png"))); // NOI18N
        jButton_Home.setText("HOME");
        jButton_Home.setIconTextGap(55);
        jButton_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_HomeMouseClicked(evt);
            }
        });
        jButton_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HomeActionPerformed(evt);
            }
        });

        jButton_ventas.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuenta.png"))); // NOI18N
        jButton_ventas.setText("VENTAS");
        jButton_ventas.setIconTextGap(45);
        jButton_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ventasMouseClicked(evt);
            }
        });
        jButton_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ventasActionPerformed(evt);
            }
        });

        jButton_Productos.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productos.png"))); // NOI18N
        jButton_Productos.setText("PRODUCTOS");
        jButton_Productos.setIconTextGap(10);
        jButton_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ProductosMouseClicked(evt);
            }
        });

        jButton_Canchas.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton_Canchas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/canchas.png"))); // NOI18N
        jButton_Canchas.setText("CANCHAS");
        jButton_Canchas.setIconTextGap(25);
        jButton_Canchas.setIgnoreRepaint(true);
        jButton_Canchas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CanchasMouseClicked(evt);
            }
        });

        jButton_Partidas.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton_Partidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Partidas.png"))); // NOI18N
        jButton_Partidas.setText("PARTIDAS");
        jButton_Partidas.setIconTextGap(30);
        jButton_Partidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PartidasMouseClicked(evt);
            }
        });

        jButton_Salir.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-izquierda.png"))); // NOI18N
        jButton_Salir.setText("Salir");
        jButton_Salir.setIconTextGap(10);
        jButton_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnmenuLayout = new javax.swing.GroupLayout(pnmenu);
        pnmenu.setLayout(pnmenuLayout);
        pnmenuLayout.setHorizontalGroup(
            pnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmenuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Partidas)
                    .addComponent(jButton_Home)
                    .addComponent(jButton_Canchas)
                    .addComponent(jButton_Productos)
                    .addComponent(jButton_ventas)
                    .addGroup(pnmenuLayout.createSequentialGroup()
                        .addComponent(jButton_Salir)
                        .addGap(28, 28, 28)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnmenuLayout.setVerticalGroup(
            pnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnmenuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton_Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_ventas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Productos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Canchas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Partidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jButton_Salir)
                .addGap(50, 50, 50))
        );

        jPanel1.add(pnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 430));
        jPanel1.add(BN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 770, 430));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 580, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ventasMouseClicked
        // TODO add your handling code here:
        pn_ventas ventas = new pn_ventas();
        
        ventas.setSize(getWidth(), getHeight());
        ventas.setLocation(5,5);
        
        BN.add(ventas, BorderLayout.CENTER);
        BN.revalidate();
        BN.repaint();
    }//GEN-LAST:event_jButton_ventasMouseClicked

    private void jButton_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ProductosMouseClicked
        // TODO add your handling code here:
        pn_productos productos = new pn_productos();
        
        productos.setSize(getWidth(), getHeight());
        productos.setLocation(5,5);
        
        BN.add(productos, BorderLayout.CENTER);
        BN.revalidate();
        BN.repaint();
    }//GEN-LAST:event_jButton_ProductosMouseClicked

    private void jButton_CanchasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CanchasMouseClicked
        // TODO add your handling code here:
        pn_canchas canchas = new pn_canchas();
        
        canchas.setSize(getWidth(), getHeight());
        canchas.setLocation(5,5);
        
        BN.add(canchas, BorderLayout.CENTER);
        BN.revalidate();
        BN.repaint();
    }//GEN-LAST:event_jButton_CanchasMouseClicked

    private void jButton_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_HomeMouseClicked
        // TODO add your handling code here:
//        Menu_Form MENU new Menu_Form ();
//        
//        MENU.setSize(getWidth(), getHeight());
//        MENU.setLocation(5,5);
//        
//        BN.add(MENU, BorderLayout.CENTER);
//        BN.revalidate();
//        BN.repaint();
    }//GEN-LAST:event_jButton_HomeMouseClicked

    private void jButton_PartidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PartidasMouseClicked
        // TODO add your handling code here:
        pn_partidas partidas = new pn_partidas();
        
        partidas.setSize(getWidth(), getHeight());
        partidas.setLocation(5,5);
        
        BN.add(partidas, BorderLayout.CENTER);
        BN.revalidate();
        BN.repaint();
    }//GEN-LAST:event_jButton_PartidasMouseClicked

    private void jButton_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_MenuMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_MenuMouseClicked

    private void jButton_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MenuActionPerformed
        // TODO add your handling code here:
       int posicion = this.pnmenu.getX();
        if (posicion > -1)
        {
            Animacion.Animacion.mover_izquierda(0, -288, 2, 2, pnmenu);
        } else 
        {
            Animacion.Animacion.mover_derecha(-288, 0, 2, 2, pnmenu);
        }
    }//GEN-LAST:event_jButton_MenuActionPerformed

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jButton_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SalirMouseClicked
        // TODO add your handling code here:
  
       //para redirigirse al login 
        
//        Login_Form lf = new Login_Form();
//        lf.setVisible(true);
//        lf.pack();
//        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        this.dispose();
    }//GEN-LAST:event_jButton_SalirMouseClicked

    private void jButton_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ventasActionPerformed

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jButton_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BN;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jButton_Canchas;
    private javax.swing.JButton jButton_Home;
    private javax.swing.JButton jButton_Menu;
    private javax.swing.JButton jButton_Partidas;
    private javax.swing.JButton jButton_Productos;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JButton jButton_ventas;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnmenu;
    // End of variables declaration//GEN-END:variables

    
}
