/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.Login_Form;
import control.BaseDatos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import java.util.LinkedList;

public class pn_productos extends javax.swing.JPanel {

    DefaultListModel modeloLista;
    LinkedList<Producto> listaProductos;

    public pn_productos() {
        initComponents();
        this.DataProducto();
        listaProductos = new LinkedList<>();
        }
        
        public void DataProducto(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id");
        model.addColumn("nombre");
        model.addColumn("fecha");
        model.addColumn("precio");

        PreparedStatement ps = null;
        ResultSet res = null;
        BaseDatos db = new BaseDatos();
        Connection conexion = (Connection) db.crearConexion();

        try {
            String query = "select * from productos";
            ps = conexion.prepareStatement(query);
            res = ps.executeQuery();
            while (res.next()){
                model.addRow(new Object[]{res.getInt (1), res.getString(2), res.getDate(3), res.getString(5)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblDatos.setModel(model);

        }

    public void agregarValor() {

    }

    public void eliminarValor() {
        int respuesta = JOptionPane.showConfirmDialog(null, " Realmente deseas quitar este producto ?");
        if (respuesta == 0) {

        }
    }

    private void getDataProducto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public class frmProducto extends javax.swing.JInternalFrame {

        DefaultTableModel dtm = new DefaultTableModel();

//        public frmProducto () {
//            initComponents();
//            String titulos [] ={"Codigo", "Nombre", "Precio", "Stock", "Estado", "Vencimiento", "Tipo", "probedor"};
//            dtm.setColumnIdentifiers(titulos);
//            tblDatos.setModel(dtm);
//           tipoPro();
//           // en el video se llamo la clase auxiar que es donde estaban los productos, en este caso es ControlProducto
//     //     ControlProducto.formatoTabla(tblDatos, new int []{05,50,60,10,10,40,100,40});
//        }
        public frmProducto() {
            initComponents();
            dtm.addColumn("id");
            dtm.addColumn("nombre");
            dtm.addColumn("fecha");
            dtm.addColumn("precio");

            dtm.addRow(new Object[]{"1", "holaa", "2020", "2000"});
            tblDatos.setModel(dtm);
        }

        void tipoPro() {

            txtCodigo.setEditable(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_nombreProduc = new javax.swing.JLabel();
        jLabel_precioProducto = new javax.swing.JLabel();
        jLabel_precioProducto1 = new javax.swing.JLabel();
        jLabel_Codigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtSt = new javax.swing.JTextField();
        textNombreP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel_buscarpnombre = new javax.swing.JLabel();
        textBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButton_Cerrar = new javax.swing.JButton();
        jButton_Editar = new javax.swing.JButton();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_nuevo = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jLabel_img_fondo = new javax.swing.JLabel();
        jButtonvolver = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_nombreProduc.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel_nombreProduc.setText("NOMBRE");
        jPanel2.add(jLabel_nombreProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel_precioProducto.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel_precioProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/precios.png"))); // NOI18N
        jLabel_precioProducto.setText("PRECIO");
        jLabel_precioProducto.setIconTextGap(20);
        jPanel2.add(jLabel_precioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 30));

        jLabel_precioProducto1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel_precioProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caja.png"))); // NOI18N
        jLabel_precioProducto1.setText("STOCK");
        jLabel_precioProducto1.setIconTextGap(20);
        jPanel2.add(jLabel_precioProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 30));

        jLabel_Codigo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel_Codigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/horizontal.png"))); // NOI18N
        jLabel_Codigo.setText("CODIGO");
        jLabel_Codigo.setIconTextGap(20);
        jPanel2.add(jLabel_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 180, 30));

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 180, 30));
        jPanel2.add(txtSt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 180, 30));
        jPanel2.add(textNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 610, 120));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel_buscarpnombre.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel_buscarpnombre.setText("Buscar por Nombre");

        textBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscarActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jButton_Cerrar.setText("Cerrar");
        jButton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jButton_Cerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_buscarpnombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBuscar)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_buscarpnombre))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Cerrar)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 610, -1));

        jButton_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ui.png"))); // NOI18N
        jButton_Editar.setText("Editar");
        jButton_Editar.setIconTextGap(20);
        jButton_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 110, -1));

        jButton_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comercio.png"))); // NOI18N
        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.setIconTextGap(10);
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 110, -1));

        jButton_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        jButton_nuevo.setText("Nuevo");
        jButton_nuevo.setIconTextGap(10);
        jButton_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, -1));

        jButton_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.setIconTextGap(10);
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 110, -1));

        jLabel_img_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel_img_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 580, 430));

        jButtonvolver.setText("Volver");
        jButtonvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonvolverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -5, 860, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
        // TODO add your handling code here:
       // para actualizar o insertar
        
        

    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CerrarActionPerformed
        // TODO add your handling code here:
        this.doLayout();
    }//GEN-LAST:event_jButton_CerrarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        
    int respuesta = JOptionPane.showConfirmDialog(null, " Realmente deseas quitar este producto ?");
      if (respuesta == 0) {
        DefaultTableModel model = (DefaultTableModel) tblDatos.getModel();
          try {
              int row = tblDatos.getSelectedRow();
              Object eve = tblDatos.getModel().getValueAt(row, 0);
              String delRow = "delete from productos where idProducto="+eve;
               PreparedStatement ps = null;
               ResultSet res = null;
               BaseDatos db = new BaseDatos();
               Connection conexion = (Connection) db.crearConexion();  
               ps = conexion.prepareStatement(delRow);
               ps.execute();
               model.removeRow(row);
               JOptionPane.showMessageDialog(null, "Eliminado !!");
               
          } catch (Exception e) {
              System.out.println("error");
          }
      }
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void jButton_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevoActionPerformed
        // TODO add your handling code here:
        // para agregar los precios 
        String nombreProducto = textNombreP.getText();
        String codigoProducto = txtCodigo.getText();
        String precioProducto = txtPrecio.getText();
        String stockProducto = txtSt.getText();
        listaProductos.add(new Producto());
          
    }//GEN-LAST:event_jButton_nuevoActionPerformed

    private void jButton_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarActionPerformed
        // TODO add your handling code here:
        // para editar los precios
        DefaultTableModel model = (DefaultTableModel) tblDatos.getModel();
        try {
            int row = tblDatos.getSelectedRow();
            Object eve = tblDatos.getModel().getValueAt(row, 0);
            String query = "select * from canchas where idCancha=" + eve;

            PreparedStatement ps = null;
            ResultSet res = null;
            BaseDatos db = new BaseDatos();
            Connection conexion = (Connection) db.crearConexion();
            ps = conexion.prepareStatement(query);
            res = ps.executeQuery();
            while (res.next()) {
                txtCodigo.setText(res.getString(1));
                txtCodigo.setEditable(false);
                txtSt.setText(res.getString(2));
            }

        } catch (Exception e) {
            System.out.println("error");
        }
        
        
    }//GEN-LAST:event_jButton_EditarActionPerformed

    private void jButtonvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonvolverActionPerformed
        // TODO add your handling code here:
        pn_ventas pv = new pn_ventas ();
        pv.setVisible(false);
        
    }//GEN-LAST:event_jButtonvolverActionPerformed

    private void textBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Cerrar;
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_nuevo;
    private javax.swing.JButton jButtonvolver;
    private javax.swing.JLabel jLabel_Codigo;
    private javax.swing.JLabel jLabel_buscarpnombre;
    private javax.swing.JLabel jLabel_img_fondo;
    private javax.swing.JLabel jLabel_nombreProduc;
    private javax.swing.JLabel jLabel_precioProducto;
    private javax.swing.JLabel jLabel_precioProducto1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textNombreP;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSt;
    // End of variables declaration//GEN-END:variables

}
