/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author familia
 */
public class pn_productos extends javax.swing.JPanel {

    DefaultListModel modeloLista;
            
    public pn_productos() {
        initComponents();
        
        modeloLista = new DefaultListModel();
        jLista.setModel(modeloLista);
    }
    
    public void agregarValor () {        
        String ID = txtcampo.getText();
        modeloLista.addElement(ID);
    }
    
    public void eliminarValor () {
      int respuesta = JOptionPane.showConfirmDialog(null, " Realmente deseas quitar este producto ?");
      if (respuesta == 0) {   
          
      int pos = jLista.getSelectedIndex();
      modeloLista.remove(pos);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_nameguia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtcampo = new javax.swing.JTextField();
        jLista = new javax.swing.JList();
        jLabel_valor = new javax.swing.JLabel();
        jButton_agregar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jLabel_img_fondo = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_nameguia.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel_nameguia.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nameguia.setText("PRODUCTOS");
        jPanel1.add(jLabel_nameguia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLista.setBackground(new java.awt.Color(0, 0, 0));
        jLista.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_valor.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel_valor.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_valor.setText("VALOR");

        jButton_agregar.setBackground(new java.awt.Color(153, 153, 153));
        jButton_agregar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        jButton_agregar.setText("AGREGAR");
        jButton_agregar.setIconTextGap(20);
        jButton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarActionPerformed(evt);
            }
        });

        jButton_eliminar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jButton_eliminar.setText("ELIMINAR");
        jButton_eliminar.setIconTextGap(20);
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_valor)
                        .addGap(47, 47, 47)
                        .addComponent(txtcampo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButton_eliminar)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcampo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_valor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLista, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_agregar)
                    .addComponent(jButton_eliminar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 410, 280));

        jLabel_img_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel_img_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarActionPerformed
        // TODO add your handling code here:
        agregarValor();
    }//GEN-LAST:event_jButton_agregarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:
        eliminarValor ();
    }//GEN-LAST:event_jButton_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_agregar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JLabel jLabel_img_fondo;
    private javax.swing.JLabel jLabel_nameguia;
    private javax.swing.JLabel jLabel_valor;
    private javax.swing.JList jLista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtcampo;
    // End of variables declaration//GEN-END:variables
}
